language: ruby
bundler_args: --without integration
rvm:
  - 1.9.2
  - 1.9.3
before_script:
  - bundle exec berks install --path vendor/cookbooks
script:
  - bundle exec "strainer test --except kitchen"
